server:
  port: ${PORT:8080}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:score}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: ${SPRING_DATA_MONGODB_DATABASE}